# goal: ti run end to end devsecops pipeline

name: DevSecOps

on:
    workflow_call:
    push:
        branches: [devsecops]

jobs:
    # job-name:
    #     workflow using that Job

    #code stage
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    # secret-scanning
    secret-scanning:
        uses: ./.github/workflows/secret-scanning.yml

    #dependency checks
    dependency-checks:
        uses: ./.github/workflows/dependency-scan.yml

    # docker checks
    docker-checks:
        uses: ./.github/workflows/docker-scans.yml
