# goal: ti run end to end devsecops pipeline 

name: DevSecOps

on: 
    push:

jobs:

    # job-name:
    #     workflow using that Job

    code-quality:
        uses: ./.github/workflows/code-quality.yml
        
    secret-scanning:
        uses: ./.github/workflows/secret-scanning.yml

        
    
