# goal - to push the images to Docker Hub

name: Docker Push

on:
    workflow_call:

jobs:
    frontend:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                folders: ["backend", "frontend"]

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Docker Setup [Login]
              uses: docker/login-action@v4
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  #   username: ${{ vars.DOCKERHUB_USERNAME }}
                  #   password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Docker Build and Push
              uses: docker/build-push-action@v7
              with:
                  context: ./${{ matrix.folders }}
                  push: true
                  tags: ghcr.io/adityamadhavi07/devboard-${{ matrix.folders }}:latest
                  #   tags: ${{ vars.DOCKERHUB_USERNAME }}/devboard-${{ matrix.folders}}:latest
